### PR TITLE
2 extra func color

### LINKED ISSUE #2: Extra Func color
It seems to me the `Extra Func` color has the same issue as described in https://github.com/edunfelt/base16-pyradio/pull/1

I have spotted these themes:
```
base16-fruit-soda
base16-brushtrees
base16-classic-light
base16-default-light
base16-edge-light
base16-google-light
```
It looks like the color `#{{base0A-hex}}` does not agree with a light background...

BTW, if you want to check the themes by yourself, this is the script I use:

```
#!/bin/bash

while true
do
    clear
    COUNT=1
    for n in *.pyradio-theme
    do
        printf '%3s/233. ' $COUNT
        echo ${n/.*/}
        ((COUNT++))
        \cp "$n" ~/.config/pyradio/themes/auto.pyradio-theme
        sleep 2.5
    done
done
```

Just paste it in the `themes` dir, and enjoy! :)
Oh, to see the `Extra Func` color, just press **\\**, or **'** :wink:

### PR DESCRIPTION
**Pull request by edunfelt**
Hi again @s-n-g, 

If you're happy with the change referenced in #2 I'll merge this? :)

### CODE REVIEW

**Comment by s-n-g** [comment]
I did not have the chance to test this one...
But, it's ok, I will and we can always revert, or... whatever :wink:

**Comment by edunfelt** [comment]
Hah I guess! It looked better than whatever color it was originally to my eyes at least. ;)

**Comment by s-n-g** [comment]
I have tested this one, and I would like it to stand out a bit more...

I have experimented with `#{{base0B-hex}}` and `#{{base08-hex}}` and I think the later would be more fitting...

Can you have a look?
Is it too much?

**Comment by edunfelt** [comment]
Ah, perhaps I misunderstood your previous comment and merged this anyway :sweat_smile: 

I did test that one as well, as `base08` is the color that we use for a few of the ui elements already. I think it's a safe bet - it stands out more than `base0D` since it's different from the statusbar so it's easier to notice that something is happening.

I don't like `base0B` as it's quite nice to leave the URL as the only element with that color (imo).

So are we good on `base08`?

**Comment by s-n-g** [comment]
Sure!
Go ahead!

**Pull request merged**
