### PR TITLE
Fixing Edit Cursor and adding 3 alternative sets of themes

### PR DESCRIPTION
**Pull request by s-n-g**
Hi @edunfelt 

Here I am again...

I have had more time to "play" with the themes, and found out that my changing the `Edit Cursor` colors was wrong; it looked good on the station editor, but not in the search field... So, I... "fixed" it again... :wink: 

Furthermore, I nave added 3 alternative sets of themes, just playing with interchanging status bar and active station colors and such... So now there are more than 950 themes there!

I am also preparing the integration in the Theme Selection window. I really do hope you will like it!

I also wanted to take this opportunity to thank you for everything; not just for creating the themes but also for triggering me to fix the whole theming implementation! This is all because of you and I cannot be thankful enough!

So, I'm waiting for the update (I'm currently using my own fork), but I do want to revert as soon as you go on with the update...

Later!

### EDIT

I have just added a short guide (and a script) to install the themes even when base16 is not used...
Do have a look, my English is not perfect and I do make a lot of typos (although I try hard not to) :)

### EDIT 2

I just could not resist...

https://u.pcloud.link/publink/show?code=XZFPx4VZjjgdMd6ULMQI3il0hIfSJJ4KvP9y

### CODE REVIEW

**Comment by edunfelt** [comment]
Hi @s-n-g!

Love the changes! For some themes the `default` looked a bit boring perhaps, so having a few different options saves people the trouble of needing to manually tamper with their theme files :)

I have some suggestions for structure of the files if you don't mind. To make things easier to understand, since it seems that we now have a `default` theme, and then `default-1` where the two "main" colors are flipped, and the same thing for `default-2` and `default-3` I suggest the following names:

- `default` -> `default`
- `default-1` -> `default-alt`
- `default-2` -> `variation`
- `default-3` -> `variation-alt`

Perhaps a bit contrived, but I think it kind of works.

Furthermore, I think it would be cleaner if all themes where under `themes/` in separate subdirectories, so like:

```
default:                                                                                                                                          
  extension: .pyradio-theme
  output: themes/default
default-alt:
  extension: .pyradio-theme
  output: themes/default-alt
variation:
  extension: .pyradio-theme
  output: themes/variation
variation-alt:
 extension: .pyradio-theme
 output: themes/variation-alt
```

in the `config.yaml`.

What do you think? If you agree I could push these changes to the PR so we can keep working on it.

I'm happy to be able to contribute in some way to pyradio - it saves me so much every day while working!!

**Comment by s-n-g** [comment]
> Love the changes! For some themes the `default` looked a bit boring perhaps, so having a few different options saves people the trouble of needing to manually tamper with their theme files :)

Noooo, they were not boring...
But as I statred loading them, I noticed they were all blue-ish (the status bar and normal cursor were blue or close to blue).
So I changed that to green :); that's the `default-alt`


> I have some suggestions for structure of the files if you don't mind. To make things easier to understand, since it seems that we now have a default theme, and then default-1 where the two "main" colors are flipped, and the same thing for default-2 and default-3 I suggest the following names:

hehe
I chose these names cause they were easier to code (lazy programmer :wink: )

But, yes!
Why not?
I can work with that too!

> Furthermore, I think it would be cleaner if all themes where under themes/ in separate subdirectories, so like:

Sure!
No problem here!
Go right ahead!

I will have to adjust the script as well... but ok, no worries!

> I'm happy to be able to contribute in some way to pyradio - it saves me so much every day while working!!

:heart:

**Comment by edunfelt** [comment]
Awesome! 

Realized that I did not change the README in this one, I'm not sure if the install instructions will change now or not (aside from the name changes of directories). 

Just @ me when you think the PR is ready to merge! :)

**Comment by s-n-g** [comment]
Hi again @edunfelt 

I have just updated the `README.md` (edited the scripts and some of the text)
Please do have a look, change it as needed and go right ahead and merge it!

**Comment by edunfelt** [comment]
Alright I have made a few minor changes, mainly to the order of the README sections.

Also added some new screenshots showing the default/default-alt variations of the themes. Tell me what you think! :)

**edit:** I could make similar screenshots for the variation themes as well, and maybe put them side by side with the existing ones. :thinking: I'll try it after lunch!

**Comment by s-n-g** [comment]
> Alright I have made a few minor changes, mainly to the order of the README sections.
> 

Now the sections seem more logical :wink: 

> Also added some new screenshots showing the default/default-alt variations of the themes. Tell me what you think! :)
> 

This is great!

> **edit:** I could make similar screenshots for the variation themes as well, and maybe put them side by side with the existing ones. thinking I'll try it after lunch!

Yes, I love the idea!

**Comment by edunfelt** [comment]
@s-n-g A little bit of HTML did the trick! :)

Thank you for all your work integrating it so nicely with pyradio and the help with the installation instructions! :tada:

**Comment by s-n-g** [comment]
This is wonderful!
Now we are finally ready to publish a new release (well, I have to update the code first :wink: )!

So, we just leave it like that... and we will hopefully update when or if the `base16` guys introduce the light/dark distinction.

Thank you again!
Later!

**Pull request merged**
